-- ==============================================================================
-- FK BÁDOG - ÚJ TERMÉKEK TÁBLA (products) ÉS STORAGE MIGRÁCIÓ
-- ==============================================================================
-- Ez a script létrehozza az új `public.products` táblát a megadott Excel/táblázat 
-- kép alapján, beállítja az RLS (Row Level Security) és Storage szabályokat,
-- valamint feltölti a mintarekordokat.
-- Futtasd a Supabase Dashboard -> SQL Editor felületén!
-- ==============================================================================

-- 1. Új termékek tábla létrehozása
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cikkszam TEXT,
    megnevezes TEXT NOT NULL,
    kategoria TEXT,
    keszlet NUMERIC DEFAULT 0,
    utanrendelheto BOOLEAN DEFAULT TRUE,
    suly_g NUMERIC,
    kiszereles NUMERIC DEFAULT 1,
    bonthato BOOLEAN DEFAULT FALSE,
    mennyisegi_egyseg TEXT DEFAULT 'db',
    netto_ar NUMERIC DEFAULT 0,
    afa_kulcs NUMERIC DEFAULT 27,
    garancia TEXT,
    leiras TEXT,
    termekkep_link TEXT,
    aktiv BOOLEAN DEFAULT TRUE,
    fenyes_ar NUMERIC,
    standard_matt_ar NUMERIC,
    ultra_matt_ar NUMERIC,
    alucink_ar NUMERIC,
    slug TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexek a gyorsabb kereséshez és szűréshez
CREATE INDEX IF NOT EXISTS idx_products_kategoria ON public.products(kategoria);
CREATE INDEX IF NOT EXISTS idx_products_aktiv ON public.products(aktiv);
CREATE INDEX IF NOT EXISTS idx_products_cikkszam ON public.products(cikkszam);
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);

-- 2. RLS (Row Level Security) bekapcsolása
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Olvasási jog mindenki számára (anon és bejelentkezett felhasználók)
DROP POLICY IF EXISTS "Termékek olvasása mindenki számára" ON public.products;
CREATE POLICY "Termékek olvasása mindenki számára" 
ON public.products FOR SELECT 
TO anon, authenticated 
USING (true);

-- Adminisztráció (beszúrás, módosítás, törlés) engedélyezése az admin felülethez
DROP POLICY IF EXISTS "Termékek adminisztrációja" ON public.products;
CREATE POLICY "Termékek adminisztrációja" 
ON public.products FOR ALL 
TO anon, authenticated 
USING (true) 
WITH CHECK (true);

-- 3. Storage bucket beállítása termékképekhez
INSERT INTO storage.buckets (id, name, public) 
VALUES ('termekek', 'termekek', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage RLS szabályok (képfeltöltés és megtekintés)
DROP POLICY IF EXISTS "Termék képek publikus megtekintése" ON storage.objects;
CREATE POLICY "Termék képek publikus megtekintése" 
ON storage.objects FOR SELECT 
TO anon, authenticated 
USING (bucket_id = 'termekek');

DROP POLICY IF EXISTS "Termék képek feltöltése és kezelése" ON storage.objects;
CREATE POLICY "Termék képek feltöltése és kezelése" 
ON storage.objects FOR ALL 
TO anon, authenticated 
USING (bucket_id = 'termekek') 
WITH CHECK (bucket_id = 'termekek');

-- 4. Kép szerinti mintaadatok rögzítése
INSERT INTO public.products (
    id, cikkszam, megnevezes, kategoria, keszlet, utanrendelheto, 
    suly_g, kiszereles, bonthato, mennyisegi_egyseg, netto_ar, 
    afa_kulcs, garancia, leiras, termekkep_link, aktiv, 
    fenyes_ar, standard_matt_ar, ultra_matt_ar, alucink_ar, slug
) VALUES 
(
    1,
    '[26]-261--0603-00001',
    '(Opel) lemezcsavar horganyzott 4,2x16',
    'Csavarok > Opel Csavarok',
    970,
    TRUE,
    1.8,
    1.0,
    FALSE,
    'db',
    11.02,
    27,
    'FÉL ÉV',
    'Kültéri, opelcsavar horg. cinkezett. Minden fémfajta rögzítéséhez használható trapézlemez, cserepeslemez, egyéb burkolóelemekhez. Tartós és időjárásálló kivitel.',
    'https://danddrhqkrxgyzhqvhec.supabase.co/storage/v1/object/public/termekek/ALFA.webp',
    TRUE,
    NULL,
    NULL,
    NULL,
    NULL,
    'opel-lemezcsavar-horganyzott-4-2x16-1'
),
(
    2,
    'TL-T18-001',
    'T18 - Trapézlemez egyedi méretben',
    'Trapézlemezek',
    1000,
    TRUE,
    NULL,
    1.0,
    FALSE,
    'm2',
    2300,
    27,
    '10 ÉV',
    'Prémium minőségű T18 trapézlemez tetőre és homlokzatra egyedi hosszméretben gyártva, többféle bevonattal.',
    'https://danddrhqkrxgyzhqvhec.supabase.co/storage/v1/object/public/termekek/STIGMA.webp',
    TRUE,
    2500,
    2700,
    3050,
    2750,
    't18-trapezlemez-egyedi-meretben-2'
),
(
    3,
    'BP2-ALFA-001',
    'ALFA Klasszikus Tetőcserép Lemez',
    'Classic Series',
    450,
    TRUE,
    4500,
    1.0,
    FALSE,
    'm2',
    3490,
    27,
    '30 ÉV',
    'Klasszikus vonalvezetésű cserepeslemez, tartós bevonattal, kiváló viharállósággal és egyszerű szerelhetőséggel.',
    'https://danddrhqkrxgyzhqvhec.supabase.co/storage/v1/object/public/termekek/ALFA.webp',
    TRUE,
    3490,
    3890,
    4290,
    3990,
    'alfa-klasszikus-tetocserep-lemez-3'
),
(
    4,
    'BP2-IZI-001',
    'IZI ROOF Moduláris Tetőfedő Lemez',
    'Modular Series',
    320,
    TRUE,
    3800,
    1.0,
    FALSE,
    'm2',
    4190,
    27,
    '40 ÉV',
    'Innovatív, moduláris cserepeslemez rejtett rögzítéssel és egyedülálló Z-lock technológiával.',
    'https://danddrhqkrxgyzhqvhec.supabase.co/storage/v1/object/public/termekek/IZI%20ROOF.jpg',
    TRUE,
    4190,
    4650,
    5100,
    4700,
    'izi-roof-modularis-tetofedo-lemez-4'
),
(
    5,
    'BP2-LIN-001',
    'LINEA Modern Profillemez',
    'Linea',
    280,
    TRUE,
    4200,
    1.0,
    FALSE,
    'm2',
    3890,
    27,
    '30 ÉV',
    'Letisztult, szögletes bordázatú prémium lemez modern építészeti megjelenéshez.',
    'https://danddrhqkrxgyzhqvhec.supabase.co/storage/v1/object/public/termekek/GAMMA.webp',
    TRUE,
    3890,
    4250,
    4690,
    4300,
    'linea-modern-profillemez-5'
),
(
    6,
    'ACC-KIEG-001',
    'Kúpcserép elem horganyzott',
    'Kiegészítők',
    150,
    TRUE,
    1200,
    1.0,
    FALSE,
    'fm',
    1850,
    27,
    '10 ÉV',
    'Standard szegélyező és gerincelem trapéz- és cserepeslemezek tetőgerinc lezárásához.',
    'https://danddrhqkrxgyzhqvhec.supabase.co/storage/v1/object/public/termekek/BAVARIA%20Roof.webp',
    TRUE,
    1850,
    2100,
    2350,
    1950,
    'kupcserep-elem-horganyzott-6'
)
ON CONFLICT (id) DO UPDATE SET
    cikkszam = EXCLUDED.cikkszam,
    megnevezes = EXCLUDED.megnevezes,
    kategoria = EXCLUDED.kategoria,
    keszlet = EXCLUDED.keszlet,
    utanrendelheto = EXCLUDED.utanrendelheto,
    suly_g = EXCLUDED.suly_g,
    kiszereles = EXCLUDED.kiszereles,
    bonthato = EXCLUDED.bonthato,
    mennyisegi_egyseg = EXCLUDED.mennyisegi_egyseg,
    netto_ar = EXCLUDED.netto_ar,
    afa_kulcs = EXCLUDED.afa_kulcs,
    garancia = EXCLUDED.garancia,
    leiras = EXCLUDED.leiras,
    termekkep_link = EXCLUDED.termekkep_link,
    aktiv = EXCLUDED.aktiv,
    fenyes_ar = EXCLUDED.fenyes_ar,
    standard_matt_ar = EXCLUDED.standard_matt_ar,
    ultra_matt_ar = EXCLUDED.ultra_matt_ar,
    alucink_ar = EXCLUDED.alucink_ar,
    slug = EXCLUDED.slug;

-- Sequence érték szinkronizálása a legmagasabb ID-hoz
SELECT setval(pg_get_serial_sequence('public.products', 'id'), COALESCE(MAX(id), 1)) FROM public.products;
